<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Authors>Evan Minton</Authors>
    <Product>ArtNet</Product>
    <Version>1.0.0</Version>
    <Copyright>Art-Net™ Designed by and Copyright Artistic Licence</Copyright>
  </PropertyGroup>
</Project>
